export const JST04_RA_1mm = (
  <footprint name="jstsh4_ra_1mm">
    <smtpad
      portHints={["pin1"]}
      pcbX="-1.5mm"
      pcbY="0mm"
      width="0.6mm"
      height="1.35mm"
      shape="rect"
    />
    <smtpad
      portHints={["pin2"]}
      pcbX="-0.5mm"
      pcbY="0mm"
      width="0.6mm"
      height="1.35mm"
      shape="rect"
    />
    <smtpad
      portHints={["pin3"]}
      pcbX="0.5mm"
      pcbY="0mm"
      width="0.6mm"
      height="1.35mm"
      shape="rect"
    />
    <smtpad
      portHints={["pin4"]}
      pcbX="1.5mm"
      pcbY="0mm"
      width="0.6mm"
      height="1.35mm"
      shape="rect"
    />
    <smtpad
      portHints={["NC2"]}
      pcbX="-2.8mm"
      pcbY="-3.675mm"
      width="1.2mm"
      height="2.0mm"
      shape="rect"
    />
    <smtpad
      portHints={["NC1"]}
      pcbX="2.8mm"
      pcbY="-3.675mm"
      width="1.2mm"
      height="2.0mm"
      shape="rect"
    />
  </footprint>
)

export const VL53L5CX_footprint = (
  <footprint name="vl53l5cx">
    <smtpad
      portHints={["pin1"]}
      pcbX="2.25mm"
      pcbY="-1.05mm"
      width="0.6mm"
      height="0.6mm"
      shape="rect"
    />
    <smtpad
      portHints={["pin2"]}
      pcbX="1.5mm"
      pcbY="-1.05mm"
      width="0.6mm"
      height="0.6mm"
      shape="rect"
    />
    <smtpad
      portHints={["pin3"]}
      pcbX="0.75mm"
      pcbY="-1.05mm"
      width="0.6mm"
      height="0.6mm"
      shape="rect"
    />
    <smtpad
      portHints={["pin4"]}
      pcbX="0mm"
      pcbY="-1.05mm"
      width="0.6mm"
      height="0.6mm"
      shape="rect"
    />
    <smtpad
      portHints={["pin5"]}
      pcbX="-0.75mm"
      pcbY="-1.05mm"
      width="0.6mm"
      height="0.6mm"
      shape="rect"
    />
    <smtpad
      portHints={["pin6"]}
      pcbX="-1.5mm"
      pcbY="-1.05mm"
      width="0.6mm"
      height="0.6mm"
      shape="rect"
    />
    <smtpad
      portHints={["pin7"]}
      pcbX="-2.25mm"
      pcbY="-1.05mm"
      width="0.6mm"
      height="0.6mm"
      shape="rect"
    />
    <smtpad
      portHints={["pin8"]}
      pcbX="2.25mm"
      pcbY="1.05mm"
      width="0.6mm"
      height="0.6mm"
      shape="rect"
    />
    <smtpad
      portHints={["pin9"]}
      pcbX="1.5mm"
      pcbY="1.05mm"
      width="0.6mm"
      height="0.6mm"
      shape="rect"
    />
    <smtpad
      portHints={["pin10"]}
      pcbX="0.75mm"
      pcbY="1.05mm"
      width="0.6mm"
      height="0.6mm"
      shape="rect"
    />
    <smtpad
      portHints={["pin11"]}
      pcbX="0mm"
      pcbY="1.05mm"
      width="0.6mm"
      height="0.6mm"
      shape="rect"
    />
    <smtpad
      portHints={["pin12"]}
      pcbX="-0.75mm"
      pcbY="1.05mm"
      width="0.6mm"
      height="0.6mm"
      shape="rect"
    />
    <smtpad
      portHints={["pin13"]}
      pcbX="-1.5mm"
      pcbY="1.05mm"
      width="0.6mm"
      height="0.6mm"
      shape="rect"
    />
    <smtpad
      portHints={["pin14"]}
      pcbX="-2.25mm"
      pcbY="1.05mm"
      width="0.6mm"
      height="0.6mm"
      shape="rect"
    />
    <smtpad
      portHints={["pin15"]}
      pcbX="2.65mm"
      pcbY="0mm"
      width="0.6mm"
      height="0.6mm"
      shape="rect"
    />
    <smtpad
      portHints={["pin16"]}
      pcbX="-2.65mm"
      pcbY="0mm"
      width="0.6mm"
      height="0.6mm"
      shape="rect"
    />
    <smtpad
      portHints={["thermal"]}
      pcbX="0mm"
      pcbY="0mm"
      width="2.316mm"
      height="1.2mm"
      shape="rect"
    />
  </footprint>
)

export const footprint_0603 = (
  <footprint name="0603">
    <smtpad
      portHints={["1"]}
      pcbX="-0.85mm"
      pcbY="0mm"
      width="1.1mm"
      height="1.0mm"
      shape="rect"
    />
    <smtpad
      portHints={["2"]}
      pcbX="0.85mm"
      pcbY="0mm"
      width="1.1mm"
      height="1.0mm"
      shape="rect"
    />
  </footprint>
)
