export const JumperFootprint = () => (
  <footprint name="jstsh4_ra_1mm">
    <smtpad
      portHints={["pin1"]}
      pcbX="-1.5mm"
      pcbY="0mm"
      width="0.6mm"
      height="1.35mm"
      shape="rect"
    />
    <smtpad
      portHints={["pin2"]}
      pcbX="-0.5mm"
      pcbY="0mm"
      width="0.6mm"
      height="1.35mm"
      shape="rect"
    />
    <smtpad
      portHints={["pin3"]}
      pcbX="0.5mm"
      pcbY="0mm"
      width="0.6mm"
      height="1.35mm"
      shape="rect"
    />
    <smtpad
      portHints={["pin4"]}
      pcbX="1.5mm"
      pcbY="0mm"
      width="0.6mm"
      height="1.35mm"
      shape="rect"
    />
    <smtpad
      portHints={["NC2"]}
      pcbX="-2.8mm"
      pcbY="-3.675mm"
      width="1.2mm"
      height="2.0mm"
      shape="rect"
    />
    <smtpad
      portHints={["NC1"]}
      pcbX="2.8mm"
      pcbY="-3.675mm"
      width="1.2mm"
      height="2.0mm"
      shape="rect"
    />
  </footprint>
)
