export const JST05_1MM_RA = () => {
  return (
    <footprint name="jstsh4_ra_1mm">
      <smtpad
        portHints={["pin1"]}
        pcbX="-2mm"
        pcbY="0mm"
        width="0.6mm"
        height="1.55mm"
        shape="rect"
      />
      <smtpad
        portHints={["pin2"]}
        pcbX="-1mm"
        pcbY="0mm"
        width="0.6mm"
        height="1.55mm"
        shape="rect"
      />
      <smtpad
        portHints={["pin3"]}
        pcbX="0mm"
        pcbY="0mm"
        width="0.6mm"
        height="1.55mm"
        shape="rect"
      />
      <smtpad
        portHints={["pin4"]}
        pcbX="1mm"
        pcbY="0mm"
        width="0.6mm"
        height="1.55mm"
        shape="rect"
      />
      <smtpad
        portHints={["pin5"]}
        pcbX="2mm"
        pcbY="0mm"
        width="0.6mm"
        height="1.55mm"
        shape="rect"
      />
      <smtpad
        portHints={["NC2"]}
        pcbX="-3.3mm"
        pcbY="-3.675mm"
        width="1.2mm"
        height="1.8mm"
        shape="rect"
      />
      <smtpad
        portHints={["NC1"]}
        pcbX="3.3mm"
        pcbY="-3.675mm"
        width="1.2mm"
        height="1.8mm"
        shape="rect"
      />
    </footprint>
  )
}
